spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/msv
    username: root
    password: 1234
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 560454378714-2pvpoigh48l1dn310gq7969ng63lb2h2.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
  jpa:
    hibernate:
      jdbc:
        batch_size: 1000
        order_inserts: true
        order_updates: true
      ddl-auto: update
    properties:
        show_sql: true
        format_sql: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000
  main:
    allow-bean-definition-overriding: true
  profiles:
    include: oauth
  boot:
    admin:
      url: http://localhost:8080
      client:
        url: http://localhost:8080
        username: admin
        password: admin
        instance:
          metadata:
            member.name: admin
            member.password: admin


logging.level:
  org.hibernate.SQL: debug




