spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/msv
    username: root
    password: 1234

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      jdbc:
        batch_size: 1000
        order_inserts: true
        order_updates: true
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000
  main:
    allow-bean-definition-overriding: true

springdoc:
  packages-to-scan: com.project.msv.controller
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    path: /swagger-ui
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: method

logging.level:
  org.hibernate.SQL: debug




